In [9]:
import numpy as np

from main import main

In [2]:
boxes = main()

6.0
10.0
0.5
1.5
95464.0
94503.5
52.5
0.0
0.0
16.0
0.0
77289.5
127531.5
101602.0
100441.5


In [3]:
boxes

[array([[ 796, 1096],
        [1091,  965],
        [1218, 1249],
        [ 923, 1381]], dtype=int64),
 array([[1386,  930],
        [1692,  889],
        [1733, 1198],
        [1427, 1239]], dtype=int64),
 array([[ 955,  744],
        [1204,  552],
        [1399,  804],
        [1151,  997]], dtype=int64),
 array([[280, 819],
        [399, 488],
        [776, 623],
        [658, 954]], dtype=int64),
 array([[1337,  616],
        [1383,  294],
        [1700,  340],
        [1653,  662]], dtype=int64),
 array([[ 867,  309],
        [1045,   40],
        [1320,  221],
        [1142,  490]], dtype=int64)]

In [5]:
box = boxes[0]

In [6]:
box

array([[ 796, 1096],
       [1091,  965],
       [1218, 1249],
       [ 923, 1381]], dtype=int64)

In [13]:
tan_angle = (box[1, 0] - box[0, 0]) / (box[0, 1] - box[1, 1])

In [14]:
np.arctan(tan_angle)

1.1528865615336972